export enum SocketNotification {
  LIVE_STATS_REQUEST = 'LIVE_STATS_REQUEST',
  LIVE_STATS_RESPONSE = 'LIVE_STATS_RESPONSE',
  LIVE_STATS_ERROR = 'LIVE_STATS_ERROR',
  GUEST_STATS_REQUEST = 'GUEST_STATS_REQUEST',
  GUEST_STATS_RESPONSE = 'GUEST_STATS_RESPONSE',
  GUEST_STATS_ERROR = 'GUEST_STATS_ERROR',
}
