/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/guests/{guestId}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Guest avatar
         * @description Returns the guest's avatar as a JPEG image. The response has an ETag and Cache-Control header, and a conditional request with If-None-Match returns 304. Use the avatarUrl from the live stats response, which changes when the image does.
         */
        get: operations["getGuestAvatar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live occupancy status
         * @description Returns whether the cabin is currently occupied, details about the ongoing and next reservation (dates, guest statistics, remaining/upcoming nights), and all-time totals (visits, nights, unique guests) excluding future bookings. Suitable for a smart mirror or real-time dashboard.
         */
        get: operations["getLiveStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/current-year": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current year summary
         * @description Returns a quick summary for the current calendar year: number of visits, total nights, and total driving distance to/from the cabin. Suitable for a summary card or widget.
         */
        get: operations["getCurrentYearStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Available years
         * @description Returns a sorted list of years for which reservations exist. Use this to populate a year picker in a dashboard.
         */
        get: operations["getAvailableYears"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/years/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full year statistics
         * @description Returns full statistics for a given year, including visit counts, nights, occupancy percentages (days/weeks/months), guest overview, EV statistics (distance, energy consumption, regeneration), driving time stats (avg/min/max to and from cabin), typical departure and arrival times, and a monthly breakdown for all 12 months.
         *
         *     A guest is counted as **new** in a given year if that year is the first year in which they appear in any reservation.
         */
        get: operations["getYearStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/years/{year}/months/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly statistics
         * @description Returns statistics for a specific month: visit count with comparisons against the previous 30 days, the same month last year, and the year-to-date monthly average; nights min/avg/max; occupancy percentages; guest list; and driving time and moment stats including diff vs. the previous month.
         */
        get: operations["getMonthStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/guests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Guest statistics
         * @description Returns guest statistics across all years: top 10 guests by number of visits and by total nights, gender distribution, and age group breakdown (0–12, 13–17, 18–30, 31–50, 51+). Suitable for a hall-of-fame view or demographic overview.
         */
        get: operations["getGuestStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/guests/{guestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Statistics for one guest
         * @description Placeholder: returns an empty object for now. Will return all relevant statistics for one guest, for the guest view on the smart mirror.
         */
        get: operations["getGuestDetailStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * GuestPeriodStats
         * @description Guest statistics for one period (the current year or all years), counting only started reservations up to today.
         */
        GuestPeriodStats: {
            /** @description Number of reservations the guest was part of that started in the period (arrival date). */
            totalVisits: number;
            /** @description Number of days the guest was present at the cabin in the period, up to and including today. */
            totalDays: number;
            /** @description Guest's rank by total visits among all guests in the period (1 = most). Tied guests share rank. Null if no visits. */
            visitsRank?: number | null;
            /** @description Guest's rank by total days among all guests in the period (1 = most). Tied guests share rank. Null if no visits. */
            daysRank?: number | null;
        };
        /** LiveGuestStats */
        LiveGuestStats: {
            /** @description Internal unique identifier of the guest. */
            guestId: string;
            /** @description Guest's first name. */
            firstName: string;
            /** @description Guest's last name. */
            lastName: string;
            /** @description Guest's age in the current year (current year - birthYear). */
            age: number;
            /** @description True if the guest is a family member (owner of the cabin), false for other guests. */
            isFamily: boolean;
            /** @description Relative URL to the guest's avatar image (JPEG), see GET /api/guests/{guestId}/avatar. Null if the guest has no avatar. */
            avatarUrl?: string | null;
            /** @description True if the guest has no reservations that started before this reservation. */
            isFirstVisit: boolean;
            /**
             * Format: date
             * @description Start date of the guest's first started reservation. Null if the guest has no started reservations.
             */
            firstVisitDate?: string | null;
            /**
             * Format: date
             * @description End date of the guest's last completed visit before this reservation. Null if there is no completed visit.
             */
            lastVisitDate?: string | null;
            /** @description Years in which the guest has started reservations, in descending order. */
            yearsVisited: number[];
            currentYear: components["schemas"]["GuestPeriodStats"];
            allTime: components["schemas"]["GuestPeriodStats"];
        };
        /**
         * CurrentReservationInfo
         * @description Details about the ongoing reservation. Null if the cabin is not currently occupied.
         */
        CurrentReservationInfo: {
            /**
             * Format: date
             * @description First day of the current reservation (check-in date, inclusive).
             */
            startDate: string;
            /**
             * Format: date
             * @description Last day of the current reservation (check-out date, exclusive — cabin is free from this date).
             */
            endDate: string;
            /** @description Statistics for each guest in the current reservation, ordered by current year days rank. */
            guests: components["schemas"]["LiveGuestStats"][];
            /** @description Number of nights remaining in the current reservation, from today until check-out. */
            remainingNights: number;
        } | null;
        /**
         * NextReservationInfo
         * @description Details about the next upcoming reservation. Null if no future reservation exists.
         */
        NextReservationInfo: {
            /**
             * Format: date
             * @description First day of the next reservation (check-in date, inclusive).
             */
            startDate: string;
            /**
             * Format: date
             * @description Last day of the next reservation (check-out date, exclusive).
             */
            endDate: string;
            /** @description Statistics for each guest in the next reservation, ordered by current year days rank. */
            guests: components["schemas"]["LiveGuestStats"][];
            /** @description Number of days from today until the next reservation starts. */
            daysUntil: number;
        } | null;
        /** FunFact */
        FunFact: {
            /** @description Guest the fact is about. Null for facts about the whole group or the cabin. */
            guestId?: string | null;
            /** @description Ready-to-display text in Norwegian. */
            text: string;
            /** @description Importance from 0 to 100, higher is more important. Lists are sorted by priority, descending. */
            priority: number;
        };
        /** LiveStats */
        LiveStats: {
            /** @description True if the cabin is currently occupied (a reservation has started but not yet ended). */
            isOccupied: boolean;
            currentReservation?: components["schemas"]["CurrentReservationInfo"];
            nextReservation?: components["schemas"]["NextReservationInfo"];
            /** @description Total number of reservations that have started, across all years. Future bookings are excluded. */
            allTimeVisits: number;
            /** @description Total number of nights across all reservations that have started. Future bookings are excluded. */
            allTimeNights: number;
            /** @description Total number of unique guests registered in the system. */
            allTimeUniqueGuests: number;
            /** @description Fun facts about the guests of the current reservation, sorted by priority. Empty if the cabin is not occupied. */
            guestFunFacts: components["schemas"]["FunFact"][];
            /** @description Fun facts about the cabin as a whole, sorted by priority. */
            cabinFunFacts: components["schemas"]["FunFact"][];
            /** @description Fun facts about the next upcoming reservation, sorted by priority. Empty if no future reservation exists. */
            nextVisitFunFacts: components["schemas"]["FunFact"][];
        };
        /** CurrentYearStats */
        CurrentYearStats: {
            /** @description The calendar year this summary covers. */
            year: number;
            /** @description Number of reservations that started in this calendar year. */
            visits: number;
            /** @description Total nights spent at the cabin during this calendar year, counting only nights within the year boundary. */
            totalNights: number;
            /** @description Total driving distance in kilometres for all trips to and from the cabin this year. Null if no vehicle trip data exists. */
            totalDistanceKm?: number | null;
        };
        /**
         * MonthlyVisitCount
         * @description Number of reservation starts in a given month.
         */
        MonthlyVisitCount: {
            /** @description Month number (1 = January, 12 = December). */
            monthNumber: number;
            /** @description Localised month name (e.g. "Januar"). */
            monthName: string;
            /** @description Number of reservation starts in this month. */
            visitCount: number;
        } | null;
        /**
         * YearVisitsStats
         * @description Visit count for this year with comparisons against the previous year.
         */
        YearVisitsStats: {
            /** @description Number of reservations that started in this calendar year. */
            totalVisits: number;
            /** @description Difference between this year's visit count and the previous year's visit count. Positive means more visits than last year. */
            comparedToPreviousYear: number;
            /** @description Average number of visits per calendar month (totalVisits / 12). */
            avgMonthlyVisits: number;
            /** @description Average number of guests per reservation this year. Null if there are no reservations. */
            avgGroupSize?: number | null;
            monthMostVisits?: components["schemas"]["MonthlyVisitCount"];
            monthFewestVisits?: components["schemas"]["MonthlyVisitCount"];
        };
        /**
         * MonthlyDaysCount
         * @description The month in which the single longest individual stay (by days) started this year. Null if no reservations exist.
         */
        MonthlyDaysCount: {
            /** @description Month number (1 = January, 12 = December). */
            monthNumber: number;
            /** @description Localised month name (e.g. "Januar"). */
            monthName: string;
            /** @description Duration in days of the longest individual stay that started in this month. */
            daysCount: number;
        } | null;
        /**
         * YearDaysStats
         * @description Occupied-day statistics for this year (including departure day).
         */
        YearDaysStats: {
            /** @description Total number of occupied days in this year across all reservations, counting overlapping reservations only once per day. Departure day is counted as an occupied day. */
            totalDays: number;
            /** @description Shortest stay in days (full duration, arrival and departure day included) among reservations that started in this year. Null if no reservations exist. */
            minDays?: number | null;
            /** @description Longest stay in days (full duration, arrival and departure day included) among reservations that started in this year. Null if no reservations exist. */
            maxDays?: number | null;
            /** @description Average stay in days (full duration, arrival and departure day included) among reservations that started in this year. Null if no reservations exist. */
            avgDays?: number | null;
            /** @description Difference between totalDays for this year and totalDays for the previous year. Positive means more occupied days than last year. */
            comparedToPreviousYear: number;
            monthLongestVisit?: components["schemas"]["MonthlyDaysCount"];
        };
        /**
         * YearNightsStats
         * @description Occupied-night statistics for this year (excluding departure day).
         */
        YearNightsStats: {
            /** @description Total number of occupied nights in this year across all reservations, counting overlapping reservations only once per night. Departure night is not counted. */
            totalNights: number;
            /** @description Shortest stay in nights (full duration) among reservations that started in this year. Null if no reservations exist. */
            minNights?: number | null;
            /** @description Longest stay in nights (full duration) among reservations that started in this year. Null if no reservations exist. */
            maxNights?: number | null;
            /** @description Average stay in nights (full duration) among reservations that started in this year. Null if no reservations exist. */
            avgNights?: number | null;
            /** @description Average number of occupied nights per calendar month (totalNights / 12). */
            avgMonthlyNights: number;
            /** @description Difference between totalNights for this year and totalNights for the previous year. Positive means more occupied nights than last year. */
            comparedToPreviousYear: number;
        };
        /**
         * OccupancyStats
         * @description Occupancy percentages for a period (year or month) across days, weeks and, for years, months.
         */
        OccupancyStats: {
            /** @description Percentage of calendar days in the period where the cabin was occupied, including the departure day. E.g. 25.0 means 25%. */
            dayOccupancy: number;
            /** @description Percentage of ISO weeks in the period that contained at least one occupied day. E.g. 50.0 means half of all weeks had at least one visit. */
            weekOccupancy: number;
            /** @description Percentage of the 12 calendar months in the year that contained at least one occupied day. Only present in yearly statistics, null in monthly context. */
            monthOccupancy?: number | null;
        };
        /**
         * TopGuestByDays
         * @description The guest with the most total days at the cabin in the year.
         */
        TopGuestByDays: {
            /** @description Internal unique identifier of the guest. */
            guestId: string;
            /** @description Guest's first name. */
            firstName: string;
            /** @description Guest's last name. */
            lastName: string;
            /** @description Guest's age in the reference year (ageYear - birthYear). */
            age: number;
            /** @description Number of reservations the guest was part of that started in the year (arrival date). */
            totalVisits: number;
            /** @description Total number of days the guest was present at the cabin in the year. */
            totalDays: number;
        } | null;
        /**
         * GuestVisitStats
         * @description A guest's visits and days at the cabin within a period (year or month).
         */
        GuestVisitStats: {
            /** @description Internal unique identifier of the guest. */
            guestId: string;
            /** @description Guest's first name. */
            firstName: string;
            /** @description Guest's last name. */
            lastName: string;
            /** @description Guest's age in the reference year (ageYear - birthYear). */
            age: number;
            /** @description Number of reservations the guest was part of that started in the period (arrival date). */
            totalVisits: number;
            /** @description Total number of days the guest was present at the cabin in the period, counting only days that fall within the period boundary. */
            totalDays: number;
        };
        /**
         * YearDrivingDistanceStats
         * @description Driving distance statistics for trips to, from, and at the cabin this year. Null if no vehicle trip data exists.
         */
        YearDrivingDistanceStats: {
            /** @description Total driving distance in kilometres for all trips to the cabin this year. */
            totalToCabinKm: number;
            /** @description Shortest single trip distance to the cabin in km this year. Null if no trips exist. */
            minToCabinKm?: number | null;
            /** @description Longest single trip distance to the cabin in km this year. Null if no trips exist. */
            maxToCabinKm?: number | null;
            /** @description Average trip distance to the cabin in km this year. Null if no trips exist. */
            avgToCabinKm?: number | null;
            /** @description Total driving distance in kilometres for all trips from the cabin this year. */
            totalFromCabinKm: number;
            /** @description Shortest single trip distance from the cabin in km this year. Null if no trips exist. */
            minFromCabinKm?: number | null;
            /** @description Longest single trip distance from the cabin in km this year. Null if no trips exist. */
            maxFromCabinKm?: number | null;
            /** @description Average trip distance from the cabin in km this year. Null if no trips exist. */
            avgFromCabinKm?: number | null;
            /** @description Total driving distance in kilometres for all trips at (around) the cabin this year. */
            totalAtCabinKm: number;
            /** @description Average of VehicleTrip.averageSpeed across all toCabin legs, for the fastest reservation trip to the cabin this year. Null if no trips exist. */
            minAvgSpeedToCabinKmh?: number | null;
            /** @description Average of VehicleTrip.averageSpeed across all toCabin legs, for the slowest reservation trip to the cabin this year. Null if no trips exist. */
            maxAvgSpeedToCabinKmh?: number | null;
            /** @description Mean of avgSpeedKmh across all reservations with a toCabin trip this year. Null if no trips exist. */
            avgAvgSpeedToCabinKmh?: number | null;
            /** @description Average of VehicleTrip.averageSpeed across all fromCabin legs, for the fastest reservation trip from the cabin this year. Null if no trips exist. */
            minAvgSpeedFromCabinKmh?: number | null;
            /** @description Average of VehicleTrip.averageSpeed across all fromCabin legs, for the slowest reservation trip from the cabin this year. Null if no trips exist. */
            maxAvgSpeedFromCabinKmh?: number | null;
            /** @description Mean of avgSpeedKmh across all reservations with a fromCabin trip this year. Null if no trips exist. */
            avgAvgSpeedFromCabinKmh?: number | null;
        } | null;
        /**
         * YearEvStats
         * @description Electric vehicle energy statistics for trips to and from the cabin this year. Null if no vehicle trip data exists.
         */
        YearEvStats: {
            /** @description Total energy consumed (kWh) for all trips to and from the cabin this year, derived from average consumption × distance per trip. Null if no vehicle trip data exists. */
            totalEnergyConsumedKwh?: number | null;
            /** @description Distance-weighted average energy consumption in kWh per 100 km across all trips to and from the cabin this year. Null if no vehicle trip data exists. */
            avgEnergyConsumptionKwhPer100km?: number | null;
            /** @description Total energy regenerated (kWh) through regenerative braking across all trips to and from the cabin this year. Null if no vehicle trip data exists. */
            totalEnergyRegeneratedKwh?: number | null;
        } | null;
        /**
         * YearDrivingTimeStats
         * @description Driving duration statistics (avg/min/max) for trips to and from the cabin this year. Null if no vehicle trip data exists.
         */
        YearDrivingTimeStats: {
            /** @description The calendar year these driving time statistics cover. */
            year: number;
            /** @description Average total driving duration to the cabin in minutes, summing all legs per trip (including stops). Null if no trip data exists. */
            avgToCabinMinutes?: number | null;
            /** @description Average driving duration to the cabin formatted as HH:mm. Null if no trip data exists. */
            avgToCabin?: string | null;
            /** @description Shortest total driving duration to the cabin in minutes across all trips this year. Null if no trip data exists. */
            minToCabinMinutes?: number | null;
            /** @description Shortest driving duration to the cabin formatted as HH:mm. Null if no trip data exists. */
            minToCabin?: string | null;
            /** @description Longest total driving duration to the cabin in minutes across all trips this year. Null if no trip data exists. */
            maxToCabinMinutes?: number | null;
            /** @description Longest driving duration to the cabin formatted as HH:mm. Null if no trip data exists. */
            maxToCabin?: string | null;
            /** @description Average total driving duration from the cabin in minutes, summing all legs per trip (including stops). Null if no trip data exists. */
            avgFromCabinMinutes?: number | null;
            /** @description Average driving duration from the cabin formatted as HH:mm. Null if no trip data exists. */
            avgFromCabin?: string | null;
            /** @description Shortest total driving duration from the cabin in minutes across all trips this year. Null if no trip data exists. */
            minFromCabinMinutes?: number | null;
            /** @description Shortest driving duration from the cabin formatted as HH:mm. Null if no trip data exists. */
            minFromCabin?: string | null;
            /** @description Longest total driving duration from the cabin in minutes across all trips this year. Null if no trip data exists. */
            maxFromCabinMinutes?: number | null;
            /** @description Longest driving duration from the cabin formatted as HH:mm. Null if no trip data exists. */
            maxFromCabin?: string | null;
        } | null;
        /**
         * YearDrivingMomentStats
         * @description Average departure and arrival clock times for trips to and from the cabin this year, expressed in Oslo timezone. Null if no vehicle trip data exists.
         */
        YearDrivingMomentStats: {
            /** @description The calendar year these driving moment statistics cover. */
            year: number;
            /** @description Average departure time from home (Oslo timezone) across all toCabin trips this year, expressed as minutes since midnight. E.g. 540 = 09:00. */
            avgDepartureHomeMinutes?: number | null;
            /** @description Average departure time from home formatted as HH:mm (Oslo timezone). Null if no trip data exists. */
            avgDepartureHome?: string | null;
            /** @description Average arrival time at the cabin (Oslo timezone) across all toCabin trips this year, expressed as minutes since midnight. */
            avgArrivalCabinMinutes?: number | null;
            /** @description Average arrival time at the cabin formatted as HH:mm (Oslo timezone). Null if no trip data exists. */
            avgArrivalCabin?: string | null;
            /** @description Average departure time from the cabin (Oslo timezone) across all fromCabin trips this year, expressed as minutes since midnight. */
            avgDepartureCabinMinutes?: number | null;
            /** @description Average departure time from the cabin formatted as HH:mm (Oslo timezone). Null if no trip data exists. */
            avgDepartureCabin?: string | null;
            /** @description Average arrival time back home (Oslo timezone) across all fromCabin trips this year, expressed as minutes since midnight. */
            avgArrivalHomeMinutes?: number | null;
            /** @description Average arrival time back home formatted as HH:mm (Oslo timezone). Null if no trip data exists. */
            avgArrivalHome?: string | null;
        } | null;
        /**
         * MonthVisitsStats
         * @description Visit count for this month with comparisons against other reference periods.
         */
        MonthVisitsStats: {
            /** @description Number of reservations that started in this month. */
            totalVisits: number;
            /** @description Difference between this month's visit count and the previous calendar month's visit count. Positive means more visits than last month. */
            comparedToPreviousMonth: number;
            /** @description Difference between this month's visit count and the same month in the previous year. Positive means more visits than the same month last year. */
            comparedToSameMonthLastYear: number;
            /** @description Difference between this month's visit count and the year-to-date monthly average (sum of visits Jan–this month divided by number of months so far). Positive means above average. */
            comparedToYearToDateAverage: number;
        };
        /**
         * MonthDaysStats
         * @description Occupied-day statistics for this month (including departure day).
         */
        MonthDaysStats: {
            /** @description Total number of occupied days in this month across all reservations, counting overlapping reservations only once per day. Departure day is counted as an occupied day. */
            totalDays: number;
            /** @description Shortest stay in days (full duration, arrival and departure day included) among reservations that started in this month. Null if no reservations started this month. */
            minDays?: number | null;
            /** @description Longest stay in days (full duration, arrival and departure day included) among reservations that started in this month. Null if no reservations started this month. */
            maxDays?: number | null;
            /** @description Average stay in days (full duration, arrival and departure day included) among reservations that started in this month. Null if no reservations started this month. */
            avgDays?: number | null;
            /** @description Difference between totalDays for this month and totalDays for the previous calendar month. Positive means more occupied days than last month. */
            comparedToPreviousMonth: number;
            /** @description Difference between totalDays for this month and totalDays for the same month in the previous year. Positive means more occupied days than the same month last year. */
            comparedToSameMonthLastYear: number;
        };
        /**
         * MonthNightsStats
         * @description Occupied-night statistics for this month (excluding departure day).
         */
        MonthNightsStats: {
            /** @description Total number of occupied nights in this month across all reservations, counting overlapping reservations only once per night. Departure night is not counted. */
            totalNights: number;
            /** @description Shortest stay in nights (full duration) among reservations that started in this month. Null if no reservations started this month. */
            minNights?: number | null;
            /** @description Longest stay in nights (full duration) among reservations that started in this month. Null if no reservations started this month. */
            maxNights?: number | null;
            /** @description Average stay in nights (full duration) among reservations that started in this month. Null if no reservations started this month. */
            avgNights?: number | null;
            /** @description Difference between totalNights for this month and totalNights for the previous calendar month. Positive means more occupied nights than last month. */
            comparedToPreviousMonth: number;
            /** @description Difference between totalNights for this month and totalNights for the same month in the previous year. Positive means more occupied nights than the same month last year. */
            comparedToSameMonthLastYear: number;
        };
        /**
         * MonthDrivingDistanceStats
         * @description Driving distance statistics for trips to, from, and at the cabin in this month. Null if no vehicle trip data exists.
         */
        MonthDrivingDistanceStats: {
            /** @description Total driving distance in kilometres for all trips to the cabin in this month. */
            totalToCabinKm: number;
            /** @description Shortest single trip distance to the cabin in km this month. Null if no trips exist. */
            minToCabinKm?: number | null;
            /** @description Longest single trip distance to the cabin in km this month. Null if no trips exist. */
            maxToCabinKm?: number | null;
            /** @description Average trip distance to the cabin in km this month. Null if no trips exist. */
            avgToCabinKm?: number | null;
            /** @description Total driving distance in kilometres for all trips from the cabin in this month. */
            totalFromCabinKm: number;
            /** @description Shortest single trip distance from the cabin in km this month. Null if no trips exist. */
            minFromCabinKm?: number | null;
            /** @description Longest single trip distance from the cabin in km this month. Null if no trips exist. */
            maxFromCabinKm?: number | null;
            /** @description Average trip distance from the cabin in km this month. Null if no trips exist. */
            avgFromCabinKm?: number | null;
            /** @description Total driving distance in kilometres for all trips at (around) the cabin in this month. */
            totalAtCabinKm: number;
            /** @description Average of VehicleTrip.averageSpeed across all toCabin legs, for the fastest reservation trip to the cabin this month. Null if no trips exist. */
            minAvgSpeedToCabinKmh?: number | null;
            /** @description Average of VehicleTrip.averageSpeed across all toCabin legs, for the slowest reservation trip to the cabin this month. Null if no trips exist. */
            maxAvgSpeedToCabinKmh?: number | null;
            /** @description Mean of avgSpeedKmh across all reservations with a toCabin trip this month. Null if no trips exist. */
            avgAvgSpeedToCabinKmh?: number | null;
            /** @description Average of VehicleTrip.averageSpeed across all fromCabin legs, for the fastest reservation trip from the cabin this month. Null if no trips exist. */
            minAvgSpeedFromCabinKmh?: number | null;
            /** @description Average of VehicleTrip.averageSpeed across all fromCabin legs, for the slowest reservation trip from the cabin this month. Null if no trips exist. */
            maxAvgSpeedFromCabinKmh?: number | null;
            /** @description Mean of avgSpeedKmh across all reservations with a fromCabin trip this month. Null if no trips exist. */
            avgAvgSpeedFromCabinKmh?: number | null;
        } | null;
        /**
         * MonthDrivingTimeStats
         * @description Driving duration statistics for trips to and from the cabin in this month. Null if no vehicle trip data exists.
         */
        MonthDrivingTimeStats: {
            /** @description Month number (1 = January, 12 = December). */
            monthNumber: number;
            /** @description Localised month name (e.g. "Januar"). */
            monthName: string;
            /** @description The calendar year this month belongs to. */
            year: number;
            /** @description Average total driving duration to the cabin in minutes this month, summing all legs per trip (including stops). Null if no trip data exists. */
            avgToCabinMinutes?: number | null;
            /** @description Average driving duration to the cabin formatted as HH:mm. Null if no trip data exists. */
            avgToCabin?: string | null;
            /** @description Shortest total driving duration to the cabin in minutes across all trips this month. Null if no trip data exists. */
            minToCabinMinutes?: number | null;
            /** @description Shortest driving duration to the cabin formatted as HH:mm. Null if no trip data exists. */
            minToCabin?: string | null;
            /** @description Longest total driving duration to the cabin in minutes across all trips this month. Null if no trip data exists. */
            maxToCabinMinutes?: number | null;
            /** @description Longest driving duration to the cabin formatted as HH:mm. Null if no trip data exists. */
            maxToCabin?: string | null;
            /** @description Average total driving duration from the cabin in minutes this month, summing all legs per trip (including stops). Null if no trip data exists. */
            avgFromCabinMinutes?: number | null;
            /** @description Average driving duration from the cabin formatted as HH:mm. Null if no trip data exists. */
            avgFromCabin?: string | null;
            /** @description Shortest total driving duration from the cabin in minutes across all trips this month. Null if no trip data exists. */
            minFromCabinMinutes?: number | null;
            /** @description Shortest driving duration from the cabin formatted as HH:mm. Null if no trip data exists. */
            minFromCabin?: string | null;
            /** @description Longest total driving duration from the cabin in minutes across all trips this month. Null if no trip data exists. */
            maxFromCabinMinutes?: number | null;
            /** @description Longest driving duration from the cabin formatted as HH:mm. Null if no trip data exists. */
            maxFromCabin?: string | null;
            /** @description Difference between avgToCabinMinutes this month and avgToCabinMinutes the previous calendar month. Positive means longer average drive than last month. Null if either month has no data. */
            diffAvgToCabinMinutesVsPrevMonth?: number | null;
            /** @description diffAvgToCabinMinutesVsPrevMonth formatted as +HH:mm or -HH:mm. Null if either month has no data. */
            diffAvgToCabinVsPrevMonth?: string | null;
            /** @description Difference between avgFromCabinMinutes this month and avgFromCabinMinutes the previous calendar month. Positive means longer average drive than last month. Null if either month has no data. */
            diffAvgFromCabinMinutesVsPrevMonth?: number | null;
            /** @description diffAvgFromCabinMinutesVsPrevMonth formatted as +HH:mm or -HH:mm. Null if either month has no data. */
            diffAvgFromCabinVsPrevMonth?: string | null;
        } | null;
        /**
         * MonthDrivingMomentStats
         * @description Average departure and arrival clock times for trips in this month, expressed in Oslo timezone. Null if no vehicle trip data exists.
         */
        MonthDrivingMomentStats: {
            /** @description Month number (1 = January, 12 = December). */
            monthNumber: number;
            /** @description Localised month name (e.g. "Januar"). */
            monthName: string;
            /** @description The calendar year this month belongs to. */
            year: number;
            /** @description Average departure time from home (Oslo timezone) across all toCabin trips in this month, expressed as minutes since midnight. */
            avgDepartureHomeMinutes?: number | null;
            /** @description Average departure time from home formatted as HH:mm (Oslo timezone). Null if no trip data exists. */
            avgDepartureHome?: string | null;
            /** @description Average arrival time at the cabin (Oslo timezone) across all toCabin trips in this month, expressed as minutes since midnight. */
            avgArrivalCabinMinutes?: number | null;
            /** @description Average arrival time at the cabin formatted as HH:mm (Oslo timezone). Null if no trip data exists. */
            avgArrivalCabin?: string | null;
            /** @description Average departure time from the cabin (Oslo timezone) across all fromCabin trips in this month, expressed as minutes since midnight. */
            avgDepartureCabinMinutes?: number | null;
            /** @description Average departure time from the cabin formatted as HH:mm (Oslo timezone). Null if no trip data exists. */
            avgDepartureCabin?: string | null;
            /** @description Average arrival time back home (Oslo timezone) across all fromCabin trips in this month, expressed as minutes since midnight. */
            avgArrivalHomeMinutes?: number | null;
            /** @description Average arrival time back home formatted as HH:mm (Oslo timezone). Null if no trip data exists. */
            avgArrivalHome?: string | null;
        } | null;
        /** MonthStats */
        MonthStats: {
            /** @description The calendar year this month belongs to. */
            year: number;
            /** @description Month number (1 = January, 12 = December). */
            monthNumber: number;
            /** @description Localised month name (e.g. "Januar"). */
            monthName: string;
            visits: components["schemas"]["MonthVisitsStats"];
            days: components["schemas"]["MonthDaysStats"];
            nights: components["schemas"]["MonthNightsStats"];
            occupancy: components["schemas"]["OccupancyStats"];
            /** @description All guests present in this month, sorted by total days descending. Visits count reservations that started in this month, days count days within this month. */
            guests: components["schemas"]["GuestVisitStats"][];
            drivingDistance?: components["schemas"]["MonthDrivingDistanceStats"];
            drivingTime?: components["schemas"]["MonthDrivingTimeStats"];
            drivingMoments?: components["schemas"]["MonthDrivingMomentStats"];
        };
        /** YearStats */
        YearStats: {
            /** @description The calendar year these statistics cover. */
            year: number;
            visits: components["schemas"]["YearVisitsStats"];
            days: components["schemas"]["YearDaysStats"];
            nights: components["schemas"]["YearNightsStats"];
            occupancy: components["schemas"]["OccupancyStats"];
            topGuestByDays?: components["schemas"]["TopGuestByDays"];
            /** @description Guests who appear in this year's reservations but did not appear in any reservation in the previous year. Sorted by total days descending. */
            newGuests: components["schemas"]["GuestVisitStats"][];
            /** @description All guests present in this year, sorted by total days descending. Visits count reservations that started in this year, days count days within this year. */
            guests: components["schemas"]["GuestVisitStats"][];
            drivingDistance?: components["schemas"]["YearDrivingDistanceStats"];
            ev?: components["schemas"]["YearEvStats"];
            drivingTime?: components["schemas"]["YearDrivingTimeStats"];
            drivingMoments?: components["schemas"]["YearDrivingMomentStats"];
            /** @description Statistics broken down for each of the 12 calendar months in this year. */
            months: components["schemas"]["MonthStats"][];
        };
        /** GuestRanking */
        GuestRanking: {
            /** @description Internal unique identifier of the guest. */
            guestId: string;
            /** @description Guest's first name. */
            firstName: string;
            /** @description Guest's last name. */
            lastName: string;
            /** @description Total number of reservations the guest was part of across all years. */
            totalVisits: number;
            /** @description Total number of days the guest was present at the cabin across all years. */
            totalDays: number;
        };
        /**
         * GenderDistribution
         * @description Gender distribution across all registered guests.
         */
        GenderDistribution: {
            /** @description Number of male guests among all registered guests. */
            maleCount: number;
            /** @description Number of female guests among all registered guests. */
            femaleCount: number;
            /** @description Percentage of male guests (maleCount / total * 100), rounded to one decimal. */
            malePercent: number;
            /** @description Percentage of female guests (femaleCount / total * 100), rounded to one decimal. */
            femalePercent: number;
        };
        /** AgeGroup */
        AgeGroup: {
            /** @description Age range label (e.g. "0-12", "13-17", "18-30", "31-50", "51+"). */
            label: string;
            /** @description Number of registered guests whose current age falls within this range. */
            guestCount: number;
            /** @description Percentage of all registered guests in this age group, rounded to one decimal. */
            percent: number;
        };
        /** GuestStats */
        GuestStats: {
            /** @description Top 10 guests ranked by total number of reservation visits across all years. */
            topGuestsByVisits: components["schemas"]["GuestRanking"][];
            /** @description Top 10 guests ranked by total number of days spent at the cabin across all years. */
            topGuestsByDays: components["schemas"]["GuestRanking"][];
            genderDistribution: components["schemas"]["GenderDistribution"];
            /** @description Age group breakdown of all registered guests, using current age at time of the request. */
            ageGroups: components["schemas"]["AgeGroup"][];
        };
        /**
         * GuestDetailStats
         * @description Placeholder: no properties yet. Will hold all statistics for one guest.
         */
        GuestDetailStats: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGuestAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal unique identifier of the guest. */
                guestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The avatar image (image/jpeg). */
            200: {
                headers: {
                    ETag?: {
                        "text/plain": unknown;
                    };
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description The avatar has not changed since the ETag in If-None-Match. */
            304: {
                headers: {
                    ETag?: {
                        "text/plain": unknown;
                    };
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The guestId path parameter is missing. */
            400: {
                headers: {
                    ETag?: {
                        "text/plain": unknown;
                    };
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description The guest does not exist or has no avatar. */
            404: {
                headers: {
                    ETag?: {
                        "text/plain": unknown;
                    };
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLiveStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live occupancy status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveStats"];
                };
            };
            /** @description Unexpected server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentYearStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current year summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentYearStats"];
                };
            };
            /** @description Unexpected server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAvailableYears: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sorted list of available years. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
            /** @description Unexpected server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getYearStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The calendar year, for example 2025. */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full statistics for the requested year. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearStats"];
                };
            };
            /** @description Invalid year parameter. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    getMonthStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The calendar year, for example 2025. */
                year: number;
                /** @description The month number, 1 (January) to 12 (December). */
                month: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistics for the requested month. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthStats"];
                };
            };
            /** @description Invalid year or month parameter (month must be 1–12). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    getGuestStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Guest statistics across all years. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestStats"];
                };
            };
            /** @description Unexpected server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGuestDetailStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal unique identifier of the guest. */
                guestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistics for the requested guest. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestDetailStats"];
                };
            };
            /** @description The guest does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unexpected server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
